### ISSUE TITLE
heroku deploy failure - ruby version

### ISSUE THREAD

**Issue by bilsch** [rubycentral/cfp-app#117]
Tried to deploy to heroku a few minutes ago and the deploy failed

```
-----> Compiling Ruby/Rails
 !
 !     An error occurred while installing ruby-2.3.0
 !     
 !     Heroku recommends you use the latest supported Ruby version listed here:
 !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
 !     
 !     For more information on syntax for declaring a Ruby version see:
 !     https://devcenter.heroku.com/articles/ruby-versions
 !     
 !     
 !     Debug InformationCommand: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-16/ruby-2.3.0.tgz -s -o - | tar zxf - ' failed unexpectedly:
```

**Comment by rylanb** [comment]
Try 2.3.4 in .ruby-version for your version?

**Comment by bilsch** [comment]
Well heroku was able to build and deploy but I think I'm missing stuff because I get a 500 error. Is there any difference in the deploy link in the github readme vs doing a link to my github fork and deploying? I'm guessing the dependencies like pgsql and such are just not set up

**Comment by mghaught** [comment]
The code should be fine for this.  The issue with the 500 (or at least when I just tried this) is the migrations have not been run.  I don't know if I consider this a bug since you need to create your admin user to access the system.   Perhaps we should update the README to make it clear that while you can do a quick deploy to Heroku, you still need to initiate your database and make your admin user.
