### ISSUE TITLE
Consider disabling hard wrap

### ISSUE THREAD

**Issue by kevinburke** [rubycentral/cfp-app#26]
The submission text box is fairly wide. If I write my talk in a text editor wrapped to 80 columns, it looks fine on the "Edit Proposal" page:

<img src="https://api.monosnap.com/image/download?id=gOKildzTynAmqcCbQ8UzlukdZvZE3W" />

However, when I click "Save" and view it on the next page, the wrapping causes issues:

<img src="https://api.monosnap.com/image/download?id=Xvc6q5LhJE42NPZLPHZxSSCWwIlWsi" />

It also shows up badly in the Organizer view<sup>1</sup> (screenshot from /organizer/events/1/proposals/f4461b360b):

<img src="https://api.monosnap.com/image/download?id=IBQK9UhLCxOk668RAOZdJ47uxXOzqk" />

The relevant configuration line is here: https://github.com/rubycentral/cfp-app/blob/master/app/helpers/application_helper.rb#L25

Since it's not on by default and it's been enabled, I am assuming there is some reason for it, though as you can see, it leads to unpleasant results. I'm realizing now I probably submitted multiple talks with my text visible in the above format.

<sup>1</sup> It took a while to figure out how to get to the Reviewer section of the site; when my proposal didn't show up in the list at /reviewer/events/1/proposals, I tried logging in as a second user, couldn't figure out how to give them Organizer permissions, tried updating admin=true in the database, though the new user wasn't able to access /reviewer/events/1/proposals.

**Comment by mghaught** [comment]
Hi Kevin, I apologize for the delay in replying to this. 

My guess is the markdown formatter is adding an extra line wrap on top of your editor's new lines. The RailsConf and RubyConf teams haven't seen issue with odd line wrap so far in proposals that we've seen in 2015.  I'll make a note to have the markdown formatter options checked to see if we can get it to work in both cases.

As for the issue not seeing your own proposal, that is by design.  This allows reviewers to submit talks that can be reviewed by the rest of the team but not by the submitter.  I believe if you go to organizer view you can see all proposals, including any you personally submitted.  Reviewer mode is blind and suppose to never look at your own content while in Organizer mode you can rate and accept whatever you'd like.  Does that make sense?
